//
//  FilterDefine.swift
//  SmartAssistant
//
//  Created by Louis.B on 2019/12/5.
//  Copyright © 2019 Louis.B. All rights reserved.
//

import Foundation

let FACE_FILTERS = [
    [FaceFilter.dimPurple : "黛紫"],
    [FaceFilter.iwai : "岩井"],
    [FaceFilter.pink : "粉嫩"],
    [FaceFilter.illusion : "错觉"],
    [FaceFilter.sunlight : "暖阳"],
    [FaceFilter.romantic : "浪漫"],
    [FaceFilter.rose : "蔷薇"],
    [FaceFilter.lotus : "睡莲"],
    [FaceFilter.candyRose : "糖果玫瑰"],
    [FaceFilter.wakaba : "新叶"],
    [FaceFilter.eucalyptus : "尤加利"],
    [FaceFilter.ink : "墨"],
    [FaceFilter.roseSnow : "玫瑰初雪"],
    [FaceFilter.cherryPudding : "樱桃布丁"],
    [FaceFilter.whiteTea : "白茶"],
    [FaceFilter.sweetMint : "甜薄荷"],
    [FaceFilter.cherryRed : "樱红"],
    [FaceFilter.sundae : "圣代"],
    [FaceFilter.moscow : "莫斯科"],
    [FaceFilter.okinawa : "冲绳"],
    [FaceFilter.pinkEmerald : "粉碧"],
    [FaceFilter.mediterranean : "地中海"],
    [FaceFilter.seoul : "首尔"],
    [FaceFilter.florence : "佛罗伦萨"],
    [FaceFilter.sapporo : "札幌"],
    [FaceFilter.gardenia : "栀子"],
    [FaceFilter.tokyo : "东京"],
    [FaceFilter.showa : "昭和"],
    [FaceFilter.natural : "自然"],
    [FaceFilter.elegant : "清逸"],
    [FaceFilter.color : "染"],
    [FaceFilter.sweet : "甜美"]
]

public let FACE_COSMETICS = [
    [CosmeticType.JpBarbiePink : "日系妆:芭比粉"],
    [CosmeticType.JpClear : "日系妆:清透"],
    [CosmeticType.JpSoot : "日系妆:烟灰"],
    [CosmeticType.JpNature : "日系妆:自然"],
    [CosmeticType.JpCherryPink : "日系妆:樱花粉"],
    [CosmeticType.JpHarajukuRed : "日系妆:原宿红"],
    [CosmeticType.KrShiny : "韩妆:闪亮"],
    [CosmeticType.KrPinkPurple : "韩妆:粉紫"],
    [CosmeticType.KrPink : "韩妆:粉嫩"],
    [CosmeticType.KrNature : "韩妆:自然"],
    [CosmeticType.KrClear : "韩妆:清透"],
    [CosmeticType.KrEarth : "韩妆:大地色"],
    [CosmeticType.KrRose : "韩妆:玫瑰"],
    [CosmeticType.nature : "裸妆:自然"],
    [CosmeticType.clear : "裸妆:清透"],
    [CosmeticType.peachPink : "裸妆:桃粉"],
    [CosmeticType.orangePink : "裸妆:橘粉"],
    [CosmeticType.springSummer : "裸妆:春夏"],
    [CosmeticType.autumnWinter : "裸妆:秋冬"],
    [CosmeticType.classicRetro : "主题妆:经典复古"],
    [CosmeticType.SexyMixedRace : "主题妆:性感混血"],
    [CosmeticType.BrightEyes : "主题妆:炫彩明眸"],
    [CosmeticType.purpleCharm : "主题妆:紫色魅惑"]
]

let FACE_DECORATIONS = [
    [DecorationType.Egypt : "埃及妆"],
    [DecorationType.Brazilian : "巴西土著妆"],
    [DecorationType.Cinderella : "灰姑娘妆"],
    [DecorationType.Demon : "恶魔妆"],
    [DecorationType.WuMeiNiang : "武媚娘妆"],
    [DecorationType.StarlightLavender : "星光薰衣草"],
    [DecorationType.HuaQianGu : "花千骨"],
    [DecorationType.Zombie : "僵尸妆"],
    [DecorationType.Patriotic : "爱国妆"],
    [DecorationType.Moustache : "小胡子妆"],
    [DecorationType.BeautySheep : "美羊羊妆"],
    [DecorationType.Naruto : "火影鸣人妆"],
    [DecorationType.PekingOpera : "刀马旦妆"],
    [DecorationType.Bubble : "泡泡妆"],
    [DecorationType.PeachBlossom : "桃花妆"],
    [DecorationType.Empress : "女皇妆"],
    [DecorationType.GDragon : "权志龙"],
    [DecorationType.TeaseGirl : "撩妹妆"],
    [DecorationType.Indian : "印第安妆"],
    [DecorationType.India : "印度妆"],
    [DecorationType.CuteRabbit : "萌兔妆"],
    [DecorationType.MonkeyKing : "大圣妆"],
]

let FACE_STICKERS = [
    [StickerType.NewDay : "It's a new day"],
    [StickerType.HappyBall1 : "欢乐球吃球1"],
    [StickerType.Bonvoyage : "一路顺风,一路平安"],
    [StickerType.Enjoy : "享受Enjoy"],
    [StickerType.ChickenSpring : "Chicken Spring"],
    [StickerType.ChristmasShow : "Merry Xmas"],
    [StickerType.ChristmasSnow : "圣诞雪人"],
    [StickerType.Cat : "猫咪"],
    [StickerType.Mouse : "米老鼠"],
    [StickerType.Pig : "猪鼻子"],
    [StickerType.Comicmn : "My NAME"],
    [StickerType.CuteBaby : "可爱北鼻"],
    [StickerType.Envolope : "信封相框"],
    [StickerType.Fairytale : "童话相框"],
    [StickerType.GoodNight : "晚安"],
    [StickerType.HalloweenNight : "万圣节之夜"],
    [StickerType.LovelyDay : "lovely day"],
    [StickerType.Newyear2017 : "2017新年"],
    [StickerType.PinkSunny : "粉红阳光"],
    [StickerType.KIRAKIRA : "KIRA KIRA"],
    [StickerType.HappyBall2 : "欢乐球吃球2"],
    [StickerType.SnowWhite : "白雪"],
    [StickerType.SuperStar : "super start"],
    [StickerType.WonderfulWork : "Wonderful Work"],
    [StickerType.Cold: "Cold"],
    [StickerType.Savior: "狼人杀守卫"],
    [StickerType.Hunter: "狼人杀猎人"],
    [StickerType.Seer: "狼人杀预言家"],
    [StickerType.Villagers: "狼人杀村民"],
    [StickerType.Witch: "狼人杀女巫"],
    [StickerType.Werewolves: "狼人杀狼人"]
]
